version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    user: nobody
    ports:
      - 5000:5000
    volumes:
      - ./app.py:/usr/src/app/app.py
    command: [/usr/src/app/venv/bin/gunicorn, --bind, "0.0.0.0:5000", --log-level, debug, "app:app"]

  app2:
    container_name: app2
    image: app
    user: nobody
    ports:
      - 5555:5555
    volumes:
      - ./app2.py:/usr/src/app/app2.py
    command: [/usr/src/app/venv/bin/gunicorn, --bind, "0.0.0.0:5555", --log-level, debug, "app2:app"]

  nginx:
    container_name: nginx
    image: nginx:mainline
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - app
