version: "3"
services:
  test_app:
    container_name: test_app
    build:
      context: .
      dockerfile: ./Dockerfile
    user: nobody
    ports:
      - 5000:5000
    command: [/usr/src/app/venv/bin/gunicorn, --bind, "0.0.0.0:5000", --log-level, debug, "app:app"]

  queue:
    container_name: rabbitmq
    hostname: queue
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    container_name: flower
    image: mher/flower
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@queue//"
    command: [celery, flower, "--url_prefix=flower"]
    ports:
      - 5555:5555
    depends_on:
      - queue

  nginx:
    container_name: nginx
    image: nginx:mainline
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - test_app
      - flower
      - queue
